# Site settings
title: 丰主义
description: Windism

# User settings
username: 丰主义
user_title: 自由职业
user_description: 一个爱分享的机器人
github: windbio
email: windism@qq.com
bilibili: 3493119548984089
weibo: 7814590825