# Site settings
title: 丰主义
description: Windism

# User settings
username: 丰主义
user_description: 一个爱思考的普通人
user_title: 自由职业
github: windbio
email: windism@qq.com
bilibili: 3493119548984089
weibo: 7814590825